# 中共的干部教育与国家治理 P3-19

## 作者

俞可平^[https://baike.baidu.com/item/%E4%BF%9E%E5%8F%AF%E5%B9%B3/10229751?fr=aladdin]

* 中央编译局前副局长

## Abstract

摘要：本文简要考察了中共现行的**干部教育培训体制**、**规划**、**功能**和**主要特征**，着重分析了这一体制对于**改善中共各级干部的素质**、**增强中共的执政能力和国家治理能力的重要作用和意义**。作者认为,中共作为中国唯一的执政党,掌握着国家的核心政治权力,**其自身的素质和能力直接决定着国家的治理水平和治理的现代化**。中共的干部教育培训体系是中国国家治理体系的重要内容,一方面,**推进中国国家治理体系和治理能力的现代化,势必要求中共干部教育培训体系的现代化**;另一方面，**中共干部教育培训体系未来的改革创新,又在很大程度上将有助于推进中国共产党自身的现代化和中国国家治理的现代化**。

关键词：干部教育；执政能力；国家治理

## Intro

中国在缺乏多党竞争、三权分立和全民普选的情况下维持了转型时期的社会稳定。一个重要的原因就是**在没有改变基本政治制度的前提下，进行了重大的治理改革**。

中国国家治理能力直接反映中共治理能力。中共治理变迁反映了其从革命党到执政党的根本转变。

这一转变同干部教育制度密切相关。

## 中共的干部教育培训体系

历史传统

改革开放后：管理经济和社会事务的新的执政需要

* 邓小平：革命化、年轻化、知识化、专业化
* 更受重视，内容和方式发生实质变化

改革开放后干部教育培训特征

1. 培训机构增加
   1. 党校系统、行政学院系统、干部学院（校）
2. 高校承担了干部培训任务
3. 境外干部培训
4. 制度化
5. 内容：知识性和技能性内容大大增加
6. 教育方式：多样，实地调研、场景模拟、案例教育、互动讨论
7. 网络平台建设（干部培训网络）？

《1996-2000年全国干部教育培训规划》

## 中共的干部教育培训规划

21世纪：新阶段

* 特征：开始制定完整的干部培训规划
* 重点：县处级以上的领导干部
* 目的：提高**政治理论水平**、**科学文化素质**和**行政管理能力**，以确保小康社会目标的实现

文件进路

* 《全国干部学习培训教材建设五年规划（2003-2007）》
* 《2006-2010年全国干部教育培训规划》
* 《2010-2020年干部教育培训改革纲要》
* 《2013-2017年全国干部教育培训规划》

培训内容：马原、中特社、党性党史中国史、社会主义核心价值体系、科学发展能力培养、知识教育

* 能力培养：体制改革、经济增长、城镇化战略、民主法治、生态文明、行政管理、网络管理、危机管理、公共关系
* 知识教育：经济、政治、文化、社会、生态、哲学、历史、科技、法律、军事、国际

培训对象

* 党政干部：中组部每年500省部级，3000地厅级，500县市级，4000公务员
  * 领导每两年脱产培训一次，五年内所有公务员全员轮训
* 企业经营管理人员：包括了重点民企
* 专业技术人员
  * 中组部每年500高级专家，中宣部每年700高校学者
* 中青年干部
* 基层干部
  * 省以下党委组织部负责培训

干部教育培训体系在中国成为仅次于国民教育体系的第二大教育体系

## 中共的干部培训与治理能力

中国领导干部的素质直接决定中国国家治理状况。

中共干部教育培训的首要目的是政治性的，而非知识性的。

中共对干部的教育培训更多是一种指令性要求。--服从组织要求、培训成为晋升条件。

培训作用

1. 解放思想，转变观念，凝聚共识，形成新的政治认同
2. 修养党性，树立理想，坚定信念，培养和强化党员干部的政治忠诚
3. 接受党风党纪教育，增强政治责任感
4. 开阔视野，学习新知识，增加新技能，提高党员干部的科学文化素质
5. 实践锻炼、培养技能、增长才干、提高行动能力
6. 交流经验，相互学习，取长补短，增强干部间的协作能力

问题

1. 政治性教育效果不明显，知识教育和能力培养效果更明显
2. 投入产出比太低
3. 培训资源质量差
4. 以培训名义玩乐
5. 影响正常工作
6. 小圈子

解决

1. 将知识教育交给普通高校，将重点放在政治教育和能力培养上
2. 法制化，要依靠国家法律而不是党内法规来规范管理和预算
3. 整合机构，避免浪费
4. 改进教材

## Comment

偏描述，干部培训制度发展历程梳理得很完整。往下做需要人类学，起码需要大量访谈。

1. 「改革开放后干部教育培训特征」的各个要素都可以拉出来看效果 i.e. 境外培训
2. 高校培训：谁来教？教什么？教的怎么样？效果怎么样？
3. 培训基层干部的principle-agent problem是否存在？地方政府是否会在培训的时候夹带私货？@平西王
4. 好奇：能力培养到底谁来教？教什么？教的怎么样？效果怎么样？
   1. @湘西网宣的沙盘模拟
5. “同学会”，好像有类似的文献？在于的组会上
6. 政治教育无用的具体表现和实证方式-还需要更多论文

