# 中国高层领导小组的运作机制及其演化 P20-47

## Author

陈玲^[http://www.sppm.tsinghua.edu.cn/szdw/qzjs/26efe4891ecd98cd011ece8cc8f50002.html]

## 摘要

本文从**国家治理体系**和**政策过程**两个角度考察了中国高层领导小组的运作机制。通过对中央财经领导小组和国务院科技教育领导小组的案例研究发现，高层领导小组是高层政治家和行政官员进行**集体决策**的机构，其职能定位和运作机制是一种**正式的次级制度**。**领导小组嵌入正式的机构设置和运行机制，并创造出新的行政秩序和问责方式，以适应特定事项的治理**。领导小组是中国**适应性治理**和**共识型决策**的实现机制。其实现机制就是**通过一系列制度性的、结构化的方式来达成政策共识**。

## 序言

中国高层领导小组

* 中国共产党中央委员会和国务院设立的常设性领导小组
* “中央”、“国务院”或“国家”字头
* 地方也有领导小组，但不规范、不易统计和观察。但中央和地方领导小组具有类似的组织决策特点。
* 名义上：党的中央机构和国家政府的议事协调机构；实质上：**集体决策机构**
* 适应性治理和共识性决策的一种实现机制

**领导小组是嵌入到党政制度体制内的正式制度**

「一事一小组」

* 事本主义逻辑的行政序列和责任主体范围
* 特定范围内的共识协商和集体决策

政策过程

* 90年代中后期制度化后，高层领导小组不再单纯是领导权威的表达工具。其强化了公共决策组织的**制度特征**
  * 议程设置上涉及全面的常规性的政策议题
  * 运行方式上依托正式的政府运行机构和流程
  * 政策产出通常是纲领性和指导性的政策文件

## 领导小组在国家治理体系中的功能

### 高层领导小组的由来和演变

原则：党的领导、民主集中制

* 20c50s：党管政府体制

1958-06-10: 设立财经、政法、外事、科学、文教五个中央工作小组，对口管理相应行政和司法机关

1978: 邓-党政分开——领导小组大多侧重党内政治工作

* 1978-12 《关于党中央、国务院机构改革方案的报告》《党中央直属机构改革实施方案》
* 1993-07-02《关于印发〈关于党政机构改革的方案〉和〈关于党政机构改革方案的实施意见〉的通知》

十八届三中全会后，新的若干个高层领导小组

领导小组从政党体系到政府体系的扩散：政府机构中的**议事协调机构**

* 承接中央领导小组职能转变：如国务院防治血吸虫病工作领导小组
* 国务院新设立：如科技教育领导小组、扶贫开发领导小组

### 领导小组决策是嵌入性的正式制度

次级制度：依附于正式的组织结构建构、按照既定的正式流程和规范运行、但不具备独立的机构地位的组织制度或运行机制

领导小组通过一系列嵌入性的次级制度将决策层的**战略意图**转化为**政策共识和有效行政**，其特征有：

* 不改变既有政府组织体系和机构设置，悬浮在政府部门之上且超出单个行政部门的职责范围；领导小组成员由部门职责决定；小组成员和行政职位挂钩，不和个人挂钩
* 内部具有清晰的层次和结构，排序体现“事本主义”特征
* 以会议沟通和协商为主，但并非头脑风暴式的讨论或随意性的即时互动，遵循制度衍生而来的正是规则
* 小组的办事机构依托正式政府部门

### 高层领导小组的决策功能

视角

1. “党管政府”的制度工具
2. 党政之间、政府部门之间进行信息沟通、议事和协调的非正式机构
3. 党政小组-政党领导人施展个人权威的工具；政府小组-沟通协调工具

作者：**党和政府内的高层领导小组都是制度化、常规化的集体决策机制**

* 20c90s中后期发生了转变
* 政党和政府高级成员绝对多数重合
* 排他性地位、实质性作用

### 领导小组与适应性治理

领导小组是一种「嵌入性」的正式制度，实现适应性治理

* 组织机构的静态层面：事本主义地创造新的部门范围和排序
* 政策共识的动态层面：沟通频率和力度大大高于常规机制和国务院常务会议

## 领导小组与共识决策过程

我国的政策制定过程是共识性决策，竞争性的政策方案进行“折衷”而非“择优”。

### 中央财经领导小组

中财办主任——发改委副主任，横跨于党政之间

工作

* 自下而上：中央经济工作会议
* 自上而下：三中全会们

该小组从个人政治生命主导（陈云）的权威决策机制，转化为制度化和常规化的集体决策机制

### 国务院科技教育领导小组

1998-06， 国务院成立科技教育领导小组，作为“议事协调机构”，强调研究、讨论、审议和协调功能。

* 但依然是科技体系中的最高决策机构
* 运行频率因人而异（赵紫阳—李鹏—朱镕基—温家宝）

## 总结讨论

1. 党中央和国务院的常设性领导小组在决策功能和运行机制上并无显著差异
   1. 最高决策机构
   2. 制度化系统
   3. 集体决策
2. 高层领导小组是高层政治家和行政官员进行集体决策的机构，其职能定位和运作机制是一整套正式的制度安排。领导小组通过嵌入正式的机构设置和运行机制，并创造出新的行政秩序和问责方式，以适应特定事项的治理。领导小组是中国适应性治理和共识性决策的一种实现机制。其实现机制就是通过一系列制度性的、结构化的方式来达成政治共识。

## Comment

描述性文章，摘要和总结讨论很重要。

问题：

  1. 习时代的影响？小组是否又回归了个人权威决策机构？
  1. 运动式治理的小组可以去看看



