# 意识形态的适应性变革与回应困境：十八大后中国共产党的意识形态创新 P88-111

## 作者

Heike Holbig[^1]

## 引言

中国面临政治僵局

1. 薄熙来事件
2. 邓聿文文章[^2]

本文将分析自十八大以来中共的**意识形态领域**的创新，不仅包括了**党的基本政治理论**的创新，还包括**更为广泛的官方政治语言**的改变。并且，我将对从过去到未来的党的纲领性规划进行**叙事性**的分析。

意识形态不仅依然存在，而且对中共的政治合法性具有重要的意义。

## 意识形态与合法性

David Beetham: 意识形态在构建政治合法性的三个具体功能

* 对政治权威合理性的规范说明——回应困境
  * 合理性来源：党具有先进性
  * 困境：公众预期提高
* 对合适绩效和公共利益保护的规范说明——政绩困境
* 公共动员--民主选举和大众动员——动员困境
  * 如果意识形态创新不能与更广泛的社会现实相适应并有助于解决社会问题，党就会由于**意识形态的索然无味**和犬儒化而面临**合法性空心化**的危机。
  * 一旦党中央不能够完全控制对政治话语的**解读权**，那么**地方干部和公民**就会**使用官方语言作为一种符号权力从而实现自己的利益**，而主流意识形态的大众动员功能也相应会被削弱。

合法性并不只是控制工具，而是能随着时间变化以**响应被发现的合法性缺陷**的**动态过程**。

意识形态能否具有**适应性**，将成为一个政权的战略和策略上面临的最大挑战。

## 党的理论创新

「三个自信」理论

对治理理论的重新包装：「国家治理体系和治理能力」

谨慎

## 新领导人的官方俗语

**政治标志性话语**和**行动格言**中出现的改变更为明显。

## 意识形态时序工程

> 构建从史学角度讲得通并从意识形态角度相一致的，联系过去与未来的符号桥梁之技巧。

在「进入小康」、「全面建设小康」、「全面建成小康」即将结束的情况下，政治语言符号需要构建一个通向更远未来的桥梁。因此，新的提法“两个百年”以及“中华民族伟大复兴的中国梦”就应运而生。

意识形态时序工程的长程性

> 首先,我们需要找到关于毛泽东的一系列引用。作为非正式的政策，**官方文件往往避免对毛1949年后文献的直接引用，因为对这些文件的编辑围绕着非常复杂的政治问题**。对于毛泽东早期的文献，则没有那么敏感。现在,对于十八大后官方文件对毛的引用，主要提及的是建国前的文献。
>
> * 最经典的引用：群众路线
> * 其他的历史性引用
>   * 百年屈辱
>   * 五千年历史
>
> 中国梦：面向光辉未来的回应性承诺
>
> * 党的宣传策略似乎更乐意看到自上而下的宣传得到**自下而上的热情回应**...中国梦在公民产生了**强烈共振**

## 结论

## 评价

回应困境和政绩困境的困境分野不明显

宣传的「强烈共振」是一个可以做的题目





[^1]: https://www.giga-hamburg.de/en/team/11564488-holbig-heike/
[^2]: http://biweeklyarchive.hrichina.org/repost/2172.html

