# 发展主义与中国地方政府的战略行为体：近期调研的初步发现 P143-181

## 摘要

本文首先将论证中国是一个**发展型国家**，简要概括早期文献中与地方政府“发展主义”概念化相关的主要见解。

接着，从我们的实地考察中，研究**地方政府当前如何引导民营经济发展**，然后从**民营企业家**角度研究他们**如何看待地方政府发展主义**。

随后，我们将讨论民营企业家通过与地方官员**战略集团的互动**，在多大程度上可以**被视为一个战略群体**，以及**如何塑造地方发展型政府的政治形态**。

最后，我们得出若干结论为未来研究打下基础。

试图完成三个目标

* 考察当今地方发展型政府与20世纪80、90年代地方政府的差异；
* 考察当今地方政府的政商关系；
* 考察县乡领导干部与民营企业家之间的互动

## 导言

政府在经济和国家-社会变革中的角色[^1]

* 政府是动态经济发展的原动力，将中国经济成功引入市场经济轨道--企业家主义entrepreneurialism、发展主义
* 政府转移了改革成果，成为领导干部个人所得，使绝大多数过敏利益遭受损害--庇护主义clientelist、掠夺主义predatory

我们将地方发展主义与“战略群体”（strategic group）分析相结合，试图完成

* 考察当今地方发展型政府与20世纪80、90年代地方政府的差异；尤其考察Jean Oi等人所提出的发展型政府的特定变体——地方法团主义政府
* 考察当今地方政府的政商关系，与20世界90年代文献中所提出的“法团主义”、“企业家主义”、“庇护主义”和“掠夺主义”政府相比较，是否有所改变
* 考察县乡领导干部与民营企业家之间的互动

地方政府和民营企业家之间的关系，与地方发展主义早期相比，在过去几十年间变得更为**水平和均衡**，这意味着**市场体制日臻成熟**，民营企业家从地方政府那里获得了**自主权**

“传统”的地方政府法团主义和企业家主义让位于“**服务型政府**”，中国较发达地区的政府变成了一个**“拘谨受压抑”的发展型政府**。

中国的民营企业家正在成为一个**“形成中”的战略群体**，即一个潜在的战略群体...他们的共同利益及理性行为或许正在逐渐**改变当代中国的地方政治形态，导致地方政商关系重组**，这或许成为“**中国资本主义**”新时代的标志，可以说，这也增强了中国政治制度的调适能力。

## 中国与发展型政府范式

发展型政府

> 政治精英和官僚机构有意并准许**以自上而下的方式发展经济**的**“目的型”政府**
>
> * 这个自上而下指的应该是政府到市场
>
> 发展型政府能够有效干预经济、创建有利于市场体制建立的**制度环境**
>
> 具有独立于利益群体的**相对自主性**
>
> * 利益群体大多通过法团主义安排被吸纳进体制
>
> 具有强国家能力state capacity
>
> 常常用一种“科学概念”作为指导思想，在“理性设计的政治秩序”中体现出技术专家治国的信仰，即“**高级现代主义**”

并非只有中央政府践行高级现代主义。地方发展主义能解释中国基层政府。

* 自由决定权（政策顺序、强度；政策实验；发展模式）

Jean Oi地方法团主义

> local corporatist state
>
> 地方政府近似于一个大型多层级公司，县是总部，乡镇是地区总部，农村是子公司。中国越来越接近新兴工业化国家理想的发展模式，即根据企业在特定行业的发展潜力以及是否已经脱颖而出来进行补贴
>
> * 选择性分配原材料、发放贷款、划款专拨...
>
> 得到许可经营的企业家往往**被政府严格把控的贸易和工业协会所代表，而无任何独立行动的余地**。因此，地方政府和民营企业之间形成了**共生关系**。
>
> 中国的私营经济更接近于东亚新兴工业化国家发展型政府中的经济体，而非新古典主义经济理论中所描述的发展模式。

民营企业家是“列宁主义政治经济的囚徒”，是对管制经济的补充而非竞争。作为红色资本家，没有理由、动因和潜能去挑战共产党执政下的任何级别政府。

## 运行中的地方发展主义：近期调研的观察所得

### 地方政府主义与私营经济的发展

私营企业促进地方经济发展，衡量干部政绩，增加税收

龙头企业--规模企业--中小企业，一系列配套措施

### 地方政府和民营企业家之间的互动

（如果存在）自发性商业组织的缺失，会产生民营企业家的「原子化」。

地方控制土地、信贷、主导商会。商会的主要作用是官商沟通渠道。

* 企业家常说，这些组织的实际意义是微不足道的

民营企业内部的党组织（author认为都没用）

* 加强当地党员建设
* 提高党员质量
* 畅通沟通渠道

### 民营企业所面临的新挑战和地方政府的作用

地方政府的「担保公司」or「小额贷款公司」，为企业提供过桥资金，防止企业崩溃。

## 重估地方政商关系：民营企业家是否作为一个战略群体？

### 战略群体

> 战略群体是指在维持和增加共同获取资源的机会方面具有**共享利益**的人们所形成的彼此休戚相关的**共同体**。
>
> 战略群体瞄准政治制度来保护其资源。
>
> 其行事讲求战略，具有集体认同collective identity和团体精神esprit de corps）

### 作为战略群体的地方干部

县乡一级的领导干部构成了中国政治制度中的一个战略群体。

* 战略主要指地方政府引导政策执行的多种方式

### 作为潜在战略群体的地方企业家

大型企业家是「精明的关键行为体」intelligent key players

从我们最新调研所得数据来看，我们认为地方的民营企业家构成了一个**潜在的战略群体**，这意味着，群体成员具有共同的利益诉求，表现出相似的行为方式，但是**为了维护各自首要的特定利益，他们仍未采取集体性战略行动**。与此同时，虽然我们发现民营企业家为了企业经济稳定发展， 实现收支平衡，形成了地方政府一个重要的支持性群体( constituency)， 但是地方发展型政府在向企业施加政治压力方面仍然具有较大的自主性。

**具有相似利益、诉求和目标的民营企业家即使通过自己个人关系网单独地与领导干部接触，也能对当地的政策制定产生重大影响，而且也能够在群体内部产生群体意识和集体认同！**

## 初步结论

1. 地方法团主义依然可行
2. 民营企业家展现出了集体行动和集体意识的最初形式

## 评价

讨论地方企业家究竟是否是一个「战略群体」，应该要考虑他们是同质企业还是异质企业。如果竞争有限的政府资源，企业和企业之间的竞争是零和的。

[^1]: https://www.hup.harvard.edu/catalog.php?isbn=9780674654549&content=toc

