# 从社会管理到社会治理：话语体系变迁与政策调整 P245-271

## 作者

何增科[^1]

## 摘要

执政党和政府自2004年以来逐渐接受了**社会治理**所包含的理念，在社会管理格局中为**社会协同、公众参与**提供了政策空间和机会，并在2013年的中共十八届三中全会上接受了**“社会治理”**的概念。

与此同时，中共也在不断调整自己的政策。

十六届四中全会以来社会建设和管理的**政策内容**日益丰富，**社会组织**的发展、**社区建设**、**社会工作专业人才队伍**建设、**志愿服务体系**受到了政策鼓励和资源支持。这说明中国共产党具有很强的学习能力和很好的适应性，善于根据形势的变化适度调整自己的意识形态和政策。

另一方面，中国共产党也具有很强的**自主性和保守能力**，在吸收借鉴外部成果的同时，坚持自己的**领导地位**和政府的**主导作用**，坚守自己的改革底线。这说明，中国共产党是在努力实现保守与变革的动态平衡过程中维护自己的长期执政地位的。

## 从社会管理到社会治理：学术界的倡导

1998 《国务院机构改革方案》：社会管理

* 政府职能：宏观调控、社会管理、公共服务
* 社会管理成为与企业管理、政府行政管理并列的一种重要管理形式

1993年起的学术界：公民社会、社会中心主义倾向

1995以来：对公民社会的批判性反思，转向

* 政治社会学的实证性分析
* 治理和善治研究、制度研究

俞可平：《治理与善治引论》[^2]《治理与善治》[^3]《公民社会的兴起与政府善治》[^4]

* > 治理是指在一个既定的范围内运用权威维持秩序，满足公众的需要
  >
  > 治理的目的是在各种不同的制度关系中运用权力去引导、控制和规范公民的各种活动，以最大限度地增进公共利益。
  >
  > 治理是国家与公民社会的合作。统治只有政府一个主体。

善治就是使公共利益最大化的社会管理过程。善治是政府与公民对公共生活的合作管理。

倡导从社会管理走向社会治理和社会善治的原因

* 市场化改革+信息社会，一元化的社会管理体制难以为继
* 社会管理需要治理理念的指导
* 社会治理的主体多元
* 社会善治为评价政府提供标准

## 从社会管理到社会治理：官方话语的转变

很不错的总结

## 从社会管理到社会治理：政策的调整

社会政策

社会组织培育与监管

社区建设与社区治理

社会工作机构和社会工作人才

## 结论

## 评论

一定要多看，这个文献特别重要



[^1]: https://zh.wikipedia.org/wiki/%E4%BD%95%E5%A2%9E%E7%A7%91
[^2]: 俞可平.治理和善治引论[J].马克思主义与现实,1999(05):37-41.
[^3]: https://book.douban.com/subject/1024184/
[^4]: 俞可平 ,王颖.公民社会的兴起与政府善治[J].中国改革,2001(06):40-41.

