# 政权合法性来源与中国模式争论P318-360

## 摘要

摘要:本文通过对近期来自中国大陆的亚**洲民主动态调查数据**的严密分析，再次检视关于中国共产党政权合法性的争论。

本文根据经验资料分析评估了与合法性相关的三个关键问题：第一，中**国共产党政权在多大程度上享有基于民众支持的合法性**；第二，**什么因素**有助于维持政权合法性的政治支撑；第三，在社会经济迅速现代化的进程中**该政权能否抵御趋向自由民主的引力**。

我们主要结论是：**没有强有力的证据显示该政权的民众基础高度或唯一地取决于其突出的经济表现或其对民族主义热忱的操控。**

我们的分析为**文化主义论者**关于政权合法性基于**传统价值观念**的主张，以及对**制度主义论者**关于政治**体制运作特征**十分关键的主张，都提供了有力的支持。

## 引言

中国模式

* > 开辟了一条在市场社会主义之下通向经济现代化的独特道路（这条道路可能优于从社会主义过渡到市场经济的其他模式），而且平稳开辟了一条通向政治现代化的替代道路。
  >
  > 这一中国特有的政治模式能够不依靠代议民主的标准化要件（定期选举、多党竞争、新闻媒体自由）而获得合法性。因为它将由一套**嵌入国家革命遗产和文化传统**，且**由自身发展的共享象征体系和价值所支撑**，明显**有别于围绕个人自由和权利而建立的西方规范与价值**。

问题

1. 民众支持基础程度
2. 支持原因
3. 未来变化

## 大争论

民众支持程度：高

支持原因

* 经济发展、民族主义和持续放宽社会和经济层面的自由等政策
  * Harry Harding[^1]
    * 1978：魅力型权威转向法理型权威
    * 依赖现代化观念和民族主义
* 制度主义
  * Andrew Nathan：中国共产党政权从制度化中获得韧性
    * 政治权力交接逐渐规范化
    * 政治精英晋升中相较于派系，更多增加了精英管理因素
    * 政权内部制度的分化和功能专用化
    * 增强政治参与和政治诉求制度的建立
* 文化主义
  * 中国本土关于合法性的概念有别于西方
    * Yangqi Tong & Daniel Bell
    * 政治精英的道德品行
    * 国家对人民幸福的责任感
    * 精英统治
  * Tianjian Shi & Jie Lu
    * 中国民主更像是基于「监护权」的论述
      * 政治为民
  * 家长式的精英统治

## 关于政权合法性来源的实证分析

### 可操作性定义

整体政权支持 diffuse regime support：支持政权、通常支持政府、通常支持政府官员

对政权机构的信任 trust in regime institutions：中央政府、地方政府、法院、中国共产党、全国人大、一般政府官员、人民解放军、警察

解释变量：国家和个人状况指标、治理水平指标、政治价值和态度指标

## 评价

还行，回归表不好看。

结论简单来说是：1）中国共产党设计的制度韧性提供了政权合法性，Andrew Nathan是对的；2）国民性依然很重要

[^1]: https://www.amazon.com/Chinas-Second-Revolution-Reform-after/dp/0815734611

