# 非政府组织和分包服务：一种新的社会福利还是社会绥靖政策？P389-

## 摘要

摘要：本文第一部分概述了“胡温”时期**在福利维度上**的**工人和国家间**的**一个新型社会契约**的**渐进式发展**。

第二部分综述了**国家一劳工非政府组织间关系**，追踪了自20世纪90年代早期以来劳工非政府组织崎岖的**发展过程**以及国家一劳工非政府组织间**互动的模糊不清的性质**。

第三部分描述了**“与劳工非政府组织共舞”的国家行动**，以此来**重新设计福利制度**使其成为更广泛的修订国家和工人间社会契约战略的一部分。这一部分检验了广东省当地政府和劳工非政府组织对这一新战略方向的初步回应。该部分还注意到了地方政府和非政府组织对此模棱两可的回应。

最后一部分考虑了**该战略对治理劳工关系的影响以及劳工非政府组织的发展**。这一部分特别讨论了国家内围绕放宽公民组织边界的争论，尤其是当它涉及诸如劳工关系和关于劳工非政府组织的合并是对福利进行不涉及政治的重新设计这样的敏感领域时所产生的争论。

## Intro

本文论证了在中央政府支持下的深圳、广东和北京当地政府的这些一致提议是一个更广泛的战略的一部分。**该战略旨在重构国家和劳工之间，或者更普遍地说是国家和公民之间的社会契约。**尽管他们是**社团主义**，但是到目前为止他们和法团主义在治理社会组织的管理框架上有两种质的区别。

* 第一，**这些非政府组织力图扩展可注册的社会组织范围**，其中包括了诸如劳工非政府组织那样的闲钱的“贱民群体”
* 这些组织接下来**希望寻求政府合同来提供服务**

维持社会控制的战略举措

随后，2012年广东省取缔某些劳工非政府组织而同时与另一些非政府组织进行合作揭示了一个深思熟虑的“分清良莠”的战略。

中国劳工组织

> 趋向于较小规模和目标导向型，并不寻求大量成员 （Ford 2006:117）

## 形塑一种国家与工人间的新型社会契约

1978年的市场经济转型预示着毛泽东时代所造就的国家与工人间社会契约的逐渐瓦解。

为了缓和与劳工间的关系，政党-国家开始使用一种新型社会契约来用法律保护劳工权利、一个更有效的工会和社会福利换取他们的沉默。

社会契约的修改包含三个方面

1. 劳工保障性法案的引入
2. 中央政府向全国总工会施压，使其进一步与工人们相关联...以避免冲突
3. 创立一种新的社会福利体系来填补随着作为生产部门的“单位”的解体而产生的福利制度的空白

